# Generated by Django 5.2.5 on 2025-10-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank associated with the transaction', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_number',
            field=models.CharField(blank=True, help_text='Bank account number associated with the transaction', max_length=50),
        ),
    ]
