# Generated by Django 5.2.5 on 2025-10-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_remove_bankaccount_bank_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='Main', help_text='Name of the account (e.g., Checking, Savings)', max_length=100),
            preserve_default=False,
        ),
    ]
