# Generated by Django 5.2.5 on 2025-10-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0009_rename_account_name_bankaccount_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_number',
        ),
    ]
