# Generated by Django 5.2.5 on 2025-11-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_auto_20251023_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('trade_republic', 'Trade Republic'), ('volksbank', 'Volksbank')], help_text='Type of bank account for CSV processing', max_length=20),
        ),
    ]
